spring:
  data:
    mongodb:
      database: orderDb
      port: 27017
      host: localhost
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: debug
    order.springframework.controllers: debug
    org.hibernate: debug
  file:
    name: logs/dev_app.log

security.enable-csrf: false
security.user.name: "hatice"
security.user.password: "password"
security.user.roles: "USER"

security.oauth.client: "client"
security.oauth.secret: "{noop}secret"
security.oauth.roles: "USER"
security.oauth.grant-type: "password"
security.oauth.refresh-token: "refresh-token"
order.topic: "order_events"