spring:
  data:
    mongodb:
      database: orderDb
      port: 27017
      host: localhost
  security:
    oauth2:
      authorization:
        check-token-access: isAuthenticated()
      client:
        client-id: first-client
        client-secret: noonewilleverguess
        access-token-uri: http://localhost:8080/oauth/token
        scope: read,write

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: debug
    order.springframework.controllers: debug
    org.hibernate: debug
  file:
    name: logs/dev_app.log

security.enable-csrf: false